project_name: ra-garage

builds:
  - dir: webapp
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -s -w -X main.version={{ .Version }} -extldflags "-static"
    env:
      - CGO_ENABLED=0

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}-v{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}hf{{ end }}"
    files:
      - ./README.md
      - ./webapp/themes

dockers:
- image_templates:
  - "ghcr.io/revidian/ram-garage:v{{ .Version }}"
  - "ghcr.io/revidian/ram-garage:{{ if .IsSnapshot }}staging{{ else }}v{{ .Major }}.{{ .Minor }}{{ end }}"
  - "ghcr.io/revidian/ram-garage:latest"
  extra_files:
  - webapp/internal-data
  - webapp/themes
  dockerfile: goreleaser.Dockerfile

checksum:
  name_template: "{{ .ProjectName }}-v{{ .Version }}-checksums.txt"
