name: "Main WF"

on: push

jobs:
  unit-tests:
    runs-on: ubuntu-22.04
    env:
      TEST_RESULTS: /tmp/test-results
      DB_USER: app
      DB_PASS: APass
      DB_PORT: 9001
      DB_NAME: app
      PGUSER: app
      PGPASSWORD: APass
      PGHOST: 127.0.0.1
      PGPORT: 9001
      PGDATABASE: app
    services:
      db:
        image: postgis/postgis:17-3.5
        env:
          POSTGRES_USER: app
          POSTGRES_PASSWORD: APass
          POSTGRES_DB: app
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - "9001:5432"
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version-file: 'go.mod'
    - name: "Install Deps"
      run: |
        curl -sSL "https://github.com/magefile/mage/releases/download/v1.15.0/mage_1.15.0_Linux-64bit.tar.gz" | sudo tar -xz --no-same-owner -C /usr/local/bin mage
        mage --version
        go install github.com/jackc/tern/v2@latest
        tern version
        go install gotest.tools/gotestsum@latest
        gotestsum --version
    - run: cd webapp && mage -v test
  build-dry-run:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - uses: goreleaser/goreleaser-action@v6
      with:
        version: '2.2.0'
        args: "release --snapshot"
