name: "Trunk WF"

on:
  push:
    branches:
    - trunk

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: "${{ github.repository }}"

jobs:
  publish-alpha-build:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
    - uses: actions/checkout@v4
    - name: "Login to GHCR"
      uses: docker/login-action@v3.3.0
      with:
        registry: "${{ env.REGISTRY }}"
        username: "${{ github.actor }}"
        password: "${{ secrets.GITHUB_TOKEN }}"
    - uses: goreleaser/goreleaser-action@v6
      with:
        version: '2.2.0'
        args: "release --snapshot"
    - name: "Debug"
      run: "docker image ls"
    - name: "Publish images to GHCR"
      run: "docker image push --all-tags ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}"
